export interface Review {
  author: string;
  rating: number;
  text: string;
  timeAgo: string;
}

export interface Activity {
  id: string;
  name: string;
  category: "beach" | "mountain" | "food" | "adventure" | "culture" | "nightlife" | "chill" | "scenic" | "coffee" | "dessert";
  area: string;
  estimatedCost: number; // For 2 people (minimum)
  costMax?: number; // Upper range for 2 people
  durationMin: number;
  duration: string;
  description: string;
  vibe: ("introvert" | "extrovert" | "romantic" | "adventurous" | "chill")[];
  tags: string[];
  deals?: string;
  nearbyIds?: string[];
  image: string;
  rating: number;
  requiresCar: boolean;
  prepTips?: string[];
  websiteUrl?: string;
  menuUrl?: string;
  reviews?: Review[];
}

export interface QuizAnswer {
  personality: "introvert" | "extrovert" | "ambivert";
  setting: "beach" | "mountains" | "city" | "winelands" | "cozy-indoor";
  vibe: "nature" | "culture" | "spontaneous" | "romantic";
  energy: "chill" | "active" | "mix";
  stage: "first-date" | "early-dating" | "relationship" | "anniversary" | "birthday" | "long-term";
  food: "coffee" | "restaurant" | "street-food";
  time: "morning" | "afternoon" | "evening" | "fullday";
  hasCar: boolean;
  budget: number;
}

export const quizQuestions = [
  {
    id: "stage",
    question: "Where are you in the journey?",
    subtitle: "This helps us set the right tone",
    options: [
      { value: "first-date", label: "First Date", emoji: "🦋", description: "Making that first impression" },
      { value: "early-dating", label: "Still Early Days", emoji: "🌱", description: "A few dates in, still getting to know each other" },
      { value: "relationship", label: "In a Relationship", emoji: "💑", description: "Official & looking to keep the spark alive" },
      { value: "anniversary", label: "Anniversary / Special", emoji: "🥂", description: "Celebrating a milestone together" },
      { value: "birthday", label: "Plan Birthday Outing", emoji: "🎂", description: "Make their birthday unforgettable" },
    ],
  },
  {
    id: "personality",
    question: "What's she like?",
    subtitle: "Pick what fits her best",
    options: [
      { value: "introvert", label: "Introvert", emoji: "🌙", description: "Prefers cozy vibes & deep conversations" },
      { value: "extrovert", label: "Extrovert", emoji: "🎉", description: "Loves energy, people & excitement" },
      { value: "ambivert", label: "Bit of both", emoji: "✨", description: "She can vibe with anything" },
    ],
  },
  {
    id: "setting",
    question: "Where does she love to be?",
    subtitle: "Her happy place",
    options: [
      { value: "beach", label: "Beach & Ocean", emoji: "🏖️", description: "Waves, sand & salty air" },
      { value: "mountains", label: "Nature & Mountains", emoji: "⛰️", description: "Trails, wine farms & views" },
      { value: "city", label: "City & Culture", emoji: "🏙️", description: "Cafés, streets & buzzy spots" },
      { value: "winelands", label: "Winelands & Countryside", emoji: "🍇", description: "Wine estates, rolling hills & slow vibes" },
      { value: "cozy-indoor", label: "Cozy & Indoor", emoji: "🕯️", description: "Coffee shops, galleries & intimate spots" },
    ],
  },
  {
    id: "vibe",
    question: "What vibe are you going for?",
    subtitle: "The feeling you want to create",
    options: [
      { value: "nature", label: "Nature & Chill", emoji: "🌿", description: "Gardens, outdoors & fresh air" },
      { value: "culture", label: "Culture & Class", emoji: "🎨", description: "Wine, art & good conversation" },
      { value: "spontaneous", label: "Fun & Spontaneous", emoji: "🎯", description: "Laughs, surprises & good energy" },
      { value: "romantic", label: "Romantic", emoji: "💫", description: "Sunsets, picnics & butterflies" },
    ],
  },
  {
    id: "energy",
    question: "How active is she?",
    subtitle: "This shapes the pace of the date",
    options: [
      { value: "chill", label: "Chilled", emoji: "☕", description: "Coffee, strolls & no rush" },
      { value: "active", label: "Active", emoji: "🚀", description: "Hikes, adventures & exploring" },
      { value: "mix", label: "A bit of both", emoji: "🎯", description: "Start slow, then get moving" },
    ],
  },
  {
    id: "time",
    question: "When's the date?",
    subtitle: "Pick a time of day",
    options: [
      { value: "morning", label: "Morning", emoji: "🌅", description: "8am–12pm" },
      { value: "afternoon", label: "Afternoon", emoji: "☀️", description: "12–5pm" },
      { value: "evening", label: "Evening", emoji: "🌆", description: "5pm onwards" },
      { value: "fullday", label: "Full Day", emoji: "🌈", description: "Go all in!" },
    ],
  },
  {
    id: "hasCar",
    question: "How are you getting around?",
    subtitle: "Some spots need wheels to reach",
    options: [
      { value: "true", label: "I've got a car", emoji: "🚗", description: "Opens up winelands & hidden gems" },
      { value: "false", label: "Uber / MyCiTi", emoji: "🚕", description: "We'll keep it central & accessible" },
    ],
  },
];

// Area coordinates for Haversine distance calculation
export const areaCoordinates: Record<string, { lat: number; lng: number }> = {
  "V&A Waterfront": { lat: -33.902, lng: 18.421 },
  "Table Mountain": { lat: -33.957, lng: 18.403 },
  "Signal Hill": { lat: -33.921, lng: 18.400 },
  "Southern Suburbs": { lat: -33.988, lng: 18.432 },
  "Constantia": { lat: -34.024, lng: 18.437 },
  "Atlantic Seaboard": { lat: -33.942, lng: 18.375 },
  "Simon's Town": { lat: -34.198, lng: 18.450 },
  "Hout Bay": { lat: -34.085, lng: 18.361 },
  "CBD": { lat: -33.929, lng: 18.424 },
  "De Waterkant": { lat: -33.921, lng: 18.414 },
  "Woodstock": { lat: -33.929, lng: 18.448 },
  "Canal Walk": { lat: -33.893, lng: 18.513 },
  "Green Point": { lat: -33.904, lng: 18.406 },
  "Sea Point": { lat: -33.927, lng: 18.387 },
  "Cape Point": { lat: -34.356, lng: 18.497 },
  "Camps Bay": { lat: -33.951, lng: 18.378 },
  "Newlands": { lat: -33.988, lng: 18.458 },
  "Muizenberg": { lat: -34.109, lng: 18.471 },
  "Kalk Bay": { lat: -34.130, lng: 18.448 },
  "Stellenbosch": { lat: -33.934, lng: 18.860 },
  "Franschhoek": { lat: -33.913, lng: 19.118 },
  "Observatory": { lat: -33.937, lng: 18.472 },
  "Bo-Kaap": { lat: -33.920, lng: 18.416 },
  "Noordhoek": { lat: -34.107, lng: 18.375 },
  "Durbanville": { lat: -33.832, lng: 18.647 },
  "Bloubergstrand": { lat: -33.810, lng: 18.459 },
  "Hermanus": { lat: -34.418, lng: 19.235 },
};

// Haversine formula for accurate distance calculation
function haversineDistance(lat1: number, lng1: number, lat2: number, lng2: number): number {
  const R = 6371;
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLng = ((lng2 - lng1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) * Math.cos((lat2 * Math.PI) / 180) *
    Math.sin(dLng / 2) * Math.sin(dLng / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return Math.round(R * c * 1.3 * 10) / 10;
}

export function getDistanceBetween(area1: string, area2: string): number {
  const c1 = areaCoordinates[area1];
  const c2 = areaCoordinates[area2];
  if (!c1 || !c2) return 0;
  if (area1 === area2) return 0;
  return Math.round(haversineDistance(c1.lat, c1.lng, c2.lat, c2.lng));
}

// March 2026 petrol: R23.80/L, consumption: 9.5L/100km
export function calculatePetrolCost(distanceKm: number, pricePerLitre: number = 23.80, consumption: number = 9.5): number {
  return Math.round((distanceKm / 100) * consumption * pricePerLitre);
}

// Uber estimate: ~R3.80/km + R15 base
export function calculateUberEstimate(distanceKm: number): number {
  if (distanceKm <= 0) return 0;
  return Math.round(15 + distanceKm * 3.80);
}

export const activities: Activity[] = [
  // ─── V&A WATERFRONT ───
  {
    id: "aquarium",
    name: "Two Oceans Aquarium",
    category: "culture",
    area: "V&A Waterfront",
    estimatedCost: 500,
    costMax: 600,
    durationMin: 90,
    duration: "90 min",
    description: "Explore the wonders of the Atlantic and Indian Oceans. Perfect for a unique, memorable date.",
    vibe: ["introvert", "romantic"],
    tags: ["culture", "romantic", "indoor"],
    deals: "Book online for R20 off per person!",
    nearbyIds: ["waterfront-cruise", "zeitz-mocaa", "unframed-icecream", "waterfront-wheel"],
    image: "🐠",
    rating: 4.7,
    requiresCar: false,
    websiteUrl: "https://www.aquarium.co.za",
    reviews: [
      { author: "Thandi M.", rating: 5, text: "Took my date here and she absolutely loved the kelp forest exhibit. So romantic walking through the underwater tunnels together!", timeAgo: "2 weeks ago" },
      { author: "James K.", rating: 4, text: "Great date spot. Not too crowded on a weekday afternoon. The penguin exhibit is a must-see.", timeAgo: "1 month ago" },
      { author: "Lerato N.", rating: 5, text: "Perfect first date activity — there's always something to talk about. Highly recommend the guided tour!", timeAgo: "3 weeks ago" },
    ],
  },
  {
    id: "waterfront-cruise",
    name: "Harbour Sunset Cruise",
    category: "adventure",
    area: "V&A Waterfront",
    estimatedCost: 600,
    costMax: 800,
    durationMin: 75,
    duration: "75 min",
    description: "Sail into the sunset with Table Mountain as your backdrop. Complimentary sparkling wine included.",
    vibe: ["romantic", "chill"],
    tags: ["romantic", "scenic", "luxury"],
    deals: "Book 48hrs ahead for best availability",
    nearbyIds: ["aquarium", "zeitz-mocaa"],
    image: "⛵",
    rating: 4.8,
    requiresCar: false,
    websiteUrl: "https://www.waterfrontcharters.co.za",
    reviews: [
      { author: "Sipho D.", rating: 5, text: "Proposed to my girlfriend on this cruise! The crew was amazing and even played our song. Unforgettable.", timeAgo: "1 month ago" },
      { author: "Claire V.", rating: 5, text: "The sunset views of Table Mountain from the boat are unreal. Sparkling wine was a lovely touch.", timeAgo: "2 weeks ago" },
      { author: "Ryan P.", rating: 4, text: "Beautiful experience but book in advance — it fills up fast. The 6pm slot has the best light.", timeAgo: "3 weeks ago" },
    ],
  },
  {
    id: "zeitz-mocaa",
    name: "Zeitz MOCAA Museum",
    category: "culture",
    area: "V&A Waterfront",
    estimatedCost: 460,
    costMax: 500,
    durationMin: 90,
    duration: "90 min",
    description: "Africa's largest contemporary art museum in a stunning converted grain silo. Thought-provoking and inspiring.",
    vibe: ["introvert", "romantic"],
    tags: ["culture", "art", "indoor"],
    deals: "Free entry for SA citizens on Wednesdays!",
    nearbyIds: ["aquarium", "waterfront-cruise"],
    image: "🎨",
    rating: 4.6,
    requiresCar: false,
    websiteUrl: "https://www.zeitzmocaa.museum",
    reviews: [
      { author: "Nomsa T.", rating: 5, text: "The building itself is a masterpiece. My partner and I spent hours discussing the art. Very stimulating date.", timeAgo: "1 week ago" },
      { author: "David L.", rating: 4, text: "Free on Wednesdays for SA citizens is amazing! Some exhibits are thought-provoking and great conversation starters.", timeAgo: "2 months ago" },
    ],
  },
  {
    id: "waterfront-wheel",
    name: "Cape Wheel",
    category: "scenic",
    area: "V&A Waterfront",
    estimatedCost: 360,
    costMax: 450,
    durationMin: 30,
    duration: "30 min",
    description: "Giant observation wheel with stunning harbour and mountain views. Extra romantic in the VIP gondola with bubbly!",
    vibe: ["romantic", "chill"],
    tags: ["scenic", "romantic", "fun"],
    deals: "VIP gondola with champagne: R450 for two",
    nearbyIds: ["aquarium", "zeitz-mocaa"],
    image: "🎡",
    rating: 4.3,
    requiresCar: false,
    websiteUrl: "https://www.capewheel.co.za",
  },

  // ─── TABLE MOUNTAIN & SIGNAL HILL ───
  {
    id: "table-mountain",
    name: "Table Mountain Cable Car",
    category: "mountain",
    area: "Table Mountain",
    estimatedCost: 860,
    durationMin: 120,
    duration: "2 hours",
    description: "Ride the revolving cable car for panoramic views of Cape Town, the ocean, and beyond. A must-do experience.",
    vibe: ["adventurous", "romantic"],
    tags: ["nature", "scenic", "adventure"],
    deals: "Book online to skip the queue. Afternoon tickets from R370pp",
    image: "🏔️",
    rating: 4.9,
    requiresCar: false,
    websiteUrl: "https://www.tablemountain.net",
    reviews: [
      { author: "Anna B.", rating: 5, text: "A MUST DO! The views from the top are breathtaking. We stayed for 2 hours just taking it all in. Book online to skip the queue!", timeAgo: "1 week ago" },
      { author: "Kagiso M.", rating: 5, text: "Took my girlfriend for her birthday. She cried happy tears at the top. Best date ever.", timeAgo: "3 weeks ago" },
      { author: "Sarah W.", rating: 4, text: "Go on a clear day! We went when it was cloudy and couldn't see much. But when it's clear — absolutely magical.", timeAgo: "1 month ago" },
    ],
  },
  {
    id: "signal-hill",
    name: "Signal Hill Sunset",
    category: "scenic",
    area: "Signal Hill",
    estimatedCost: 0,
    durationMin: 90,
    duration: "90 min",
    description: "Watch the sun dip below the Atlantic from this iconic viewpoint. Bring a blanket and wine for extra romance.",
    vibe: ["romantic", "chill"],
    tags: ["romantic", "scenic", "nature", "free"],
    image: "🌅",
    rating: 4.7,
    requiresCar: true,
    prepTips: ["Bring a blanket and cushion", "Pack a bottle of wine/bubbly and glasses", "Arrive 45 min before sunset for a good spot", "Bring a Bluetooth speaker for soft music"],
    reviews: [
      { author: "Marco F.", rating: 5, text: "Best free date in Cape Town. We brought wine, cheese, and a blanket. Watched the sun go down with the city lights coming on. Pure magic.", timeAgo: "4 days ago" },
      { author: "Zanele K.", rating: 5, text: "My boyfriend surprised me here with a picnic. The views are insane! Get there early.", timeAgo: "2 weeks ago" },
    ],
  },
  {
    id: "lions-head",
    name: "Lion's Head Hike",
    category: "mountain",
    area: "Signal Hill",
    estimatedCost: 0,
    durationMin: 180,
    duration: "3 hours",
    description: "360° views of Cape Town from the summit. Best at sunset or full moon. An unforgettable adventure date!",
    vibe: ["adventurous", "extrovert"],
    tags: ["nature", "adventure", "free", "active"],
    image: "🦁",
    rating: 4.9,
    requiresCar: false,
    prepTips: ["Bring water and a headlamp if doing sunset", "Wear proper hiking shoes", "Pack a small snack for the top", "Check the full moon calendar for extra magic"],
    reviews: [
      { author: "Tom H.", rating: 5, text: "Full moon hike was INCREDIBLE! Started at 5pm, reached the top for sunset. Headlamp essential for the way down.", timeAgo: "1 week ago" },
      { author: "Palesa S.", rating: 4, text: "Challenging but worth it. My date was impressed I planned this. The chain ladder section is fun but not for the faint-hearted.", timeAgo: "3 weeks ago" },
    ],
  },

  // ─── SOUTHERN SUBURBS & CONSTANTIA ───
  {
    id: "kirstenbosch",
    name: "Kirstenbosch Gardens",
    category: "mountain",
    area: "Southern Suburbs",
    estimatedCost: 500,
    costMax: 650,
    durationMin: 150,
    duration: "2.5 hours",
    description: "World-class botanical gardens with the Boomslang tree canopy walkway. Pack a picnic for the ultimate date.",
    vibe: ["introvert", "romantic", "chill"],
    tags: ["nature", "romantic", "scenic"],
    deals: "Sunday sunset concerts in summer!",
    image: "🌿",
    rating: 4.8,
    requiresCar: true,
    prepTips: ["Pack a picnic blanket and basket", "Bring charcuterie, fruit, bread, cheese & sparkling water", "Walk the Boomslang canopy walkway together", "If she likes flowers, learn a few names to impress her"],
    websiteUrl: "https://www.sanbi.org/gardens/kirstenbosch",
    reviews: [
      { author: "Lisa R.", rating: 5, text: "We packed a full picnic — cheese, crackers, wine, strawberries. Sat on the lawn for hours. The Boomslang walkway is magical!", timeAgo: "5 days ago" },
      { author: "Thabo J.", rating: 5, text: "Sunday sunset concerts in summer are THE date activity. Buy tickets early, bring a blanket, and enjoy live music surrounded by nature.", timeAgo: "2 weeks ago" },
      { author: "Emma C.", rating: 4, text: "Beautiful gardens but can get busy on weekends. Go on a weekday morning for a quieter, more romantic experience.", timeAgo: "1 month ago" },
    ],
  },
  {
    id: "wine-tasting",
    name: "Constantia Wine Tasting",
    category: "food",
    area: "Constantia",
    estimatedCost: 440,
    costMax: 700,
    durationMin: 150,
    duration: "2.5 hours",
    description: "Historic wine estates in SA's oldest wine region. Tastings, cheese boards, and gorgeous gardens.",
    vibe: ["romantic", "chill", "introvert"],
    tags: ["culture", "romantic", "luxury", "food"],
    deals: "Groot Constantia: R120pp for 5 wines",
    image: "🍷",
    rating: 4.7,
    requiresCar: true,
    websiteUrl: "https://www.grootconstantia.co.za",
    menuUrl: "https://www.grootconstantia.co.za/simons-restaurant/",
    reviews: [
      { author: "André P.", rating: 5, text: "Groot Constantia never disappoints. The wine tasting is excellent value and the grounds are beautiful for a stroll afterwards.", timeAgo: "1 week ago" },
      { author: "Michelle D.", rating: 4, text: "We did the wine and chocolate pairing — amazing! The estate is gorgeous for photos.", timeAgo: "3 weeks ago" },
    ],
  },
  {
    id: "newlands-forest",
    name: "Newlands Forest Walk",
    category: "mountain",
    area: "Newlands",
    estimatedCost: 0,
    durationMin: 90,
    duration: "90 min",
    description: "Shady forest trails with towering trees and a gentle stream. Peaceful, quiet, and incredibly romantic.",
    vibe: ["introvert", "romantic", "chill"],
    tags: ["nature", "romantic", "free"],
    image: "🌲",
    rating: 4.5,
    requiresCar: true,
    prepTips: ["Bring water and a light jacket — it's cooler under the trees", "The contour path is gentle and perfect for chatting"],
  },

  // ─── BEACHES ───
  {
    id: "clifton-beach",
    name: "Clifton 4th Beach",
    category: "beach",
    area: "Atlantic Seaboard",
    estimatedCost: 0,
    durationMin: 150,
    duration: "2.5 hours",
    description: "Sheltered from the wind with stunning turquoise water and white sand. Cape Town's most glamorous beach.",
    vibe: ["romantic", "chill", "extrovert"],
    tags: ["beach", "romantic", "free", "scenic"],
    image: "🏖️",
    rating: 4.6,
    requiresCar: false,
    prepTips: ["Bring a beach umbrella and towels", "Pack cold drinks and snacks", "The water is freezing — brave it together for bonus points!", "Arrive early in summer for a good spot"],
    reviews: [
      { author: "Jessica M.", rating: 5, text: "The most beautiful beach in Cape Town. Sheltered from the wind. We spent the whole afternoon here with cocktails from the vendors.", timeAgo: "3 days ago" },
      { author: "Liam W.", rating: 4, text: "Water is ICE cold but the views make up for it. Pro tip: 4th beach is the most sheltered and least windy.", timeAgo: "2 weeks ago" },
    ],
  },
  {
    id: "camps-bay-beach",
    name: "Camps Bay Beach & Strip",
    category: "beach",
    area: "Camps Bay",
    estimatedCost: 0,
    durationMin: 120,
    duration: "2 hours",
    description: "Palm-lined beach with the Twelve Apostles as backdrop. Walk the strip, grab a drink at one of the beachfront restaurants.",
    vibe: ["extrovert", "romantic", "chill"],
    tags: ["beach", "scenic", "free", "romantic"],
    image: "🌴",
    rating: 4.5,
    requiresCar: false,
  },
  {
    id: "boulder-penguins",
    name: "Boulders Beach Penguins",
    category: "beach",
    area: "Simon's Town",
    estimatedCost: 440,
    durationMin: 90,
    duration: "90 min",
    description: "See the famous African penguin colony up close. A truly unique Cape Town experience she'll never forget.",
    vibe: ["romantic", "chill"],
    tags: ["nature", "scenic", "beach"],
    image: "🐧",
    rating: 4.7,
    requiresCar: true,
    websiteUrl: "https://www.sanparks.org/parks/table_mountain/tourism/attraction_boulders.php",
  },
  {
    id: "muizenberg-surf",
    name: "Muizenberg Surf Lesson",
    category: "adventure",
    area: "Muizenberg",
    estimatedCost: 1000,
    durationMin: 120,
    duration: "2 hours",
    description: "Learn to surf together on beginner-friendly waves. Colourful beach huts make the perfect photo backdrop.",
    vibe: ["adventurous", "extrovert"],
    tags: ["adventure", "beach", "active", "fun"],
    deals: "Couples lessons available — ask for a deal!",
    image: "🏄",
    rating: 4.6,
    requiresCar: true,
    websiteUrl: "https://www.garysurfschool.com",
  },
  {
    id: "muizenberg-walk",
    name: "Muizenberg Beach Walk",
    category: "beach",
    area: "Muizenberg",
    estimatedCost: 0,
    durationMin: 60,
    duration: "1 hour",
    description: "Stroll along the iconic colourful beach huts. Warm water, long sandy beach, and a relaxed False Bay vibe.",
    vibe: ["romantic", "chill"],
    tags: ["beach", "scenic", "free", "romantic"],
    image: "🎨",
    rating: 4.4,
    requiresCar: true,
  },
  {
    id: "llandudno",
    name: "Llandudno Beach",
    category: "beach",
    area: "Atlantic Seaboard",
    estimatedCost: 0,
    durationMin: 120,
    duration: "2 hours",
    description: "Secluded, stunning, and uncrowded. Massive boulders create a private paradise — perfect for a romantic escape.",
    vibe: ["romantic", "introvert", "chill"],
    tags: ["beach", "scenic", "free", "romantic"],
    image: "🪨",
    rating: 4.7,
    requiresCar: true,
  },

  // ─── SCENIC DRIVES & NATURE ───
  {
    id: "chapmans-peak",
    name: "Chapman's Peak Drive",
    category: "scenic",
    area: "Hout Bay",
    estimatedCost: 120,
    durationMin: 60,
    duration: "1 hour",
    description: "One of the world's most scenic coastal drives. Stop at viewpoints for photos and jaw-dropping ocean views.",
    vibe: ["romantic", "adventurous"],
    tags: ["scenic", "adventure", "romantic"],
    image: "🛣️",
    rating: 4.9,
    requiresCar: true,
    websiteUrl: "https://www.chapmanspeakdrive.co.za",
  },
  {
    id: "cape-point",
    name: "Cape Point Nature Reserve",
    category: "adventure",
    area: "Cape Point",
    estimatedCost: 760,
    durationMin: 240,
    duration: "4 hours",
    description: "Where the Atlantic meets the Indian Ocean. Dramatic cliffs, hiking, and the iconic lighthouse.",
    vibe: ["adventurous", "romantic"],
    tags: ["nature", "adventure", "scenic"],
    deals: "Bring a picnic — restaurants are pricey",
    image: "🌊",
    rating: 4.8,
    requiresCar: true,
    prepTips: ["Pack lunch and snacks — food inside is expensive", "Wear layers — it's windy at the point", "Walk to the old lighthouse for the best views"],
    websiteUrl: "https://www.sanparks.org/parks/table_mountain/tourism/attraction_capepoint.php",
  },
  {
    id: "noordhoek-beach",
    name: "Noordhoek Long Beach Walk",
    category: "beach",
    area: "Noordhoek",
    estimatedCost: 0,
    durationMin: 90,
    duration: "90 min",
    description: "8km of wild, untouched beach. Dramatic dunes, shipwreck views, and total serenity. Great for horse riding too!",
    vibe: ["romantic", "chill", "introvert"],
    tags: ["beach", "nature", "free", "scenic"],
    image: "🐎",
    rating: 4.6,
    requiresCar: true,
  },

  // ─── CITY / CBD / BO-KAAP ───
  {
    id: "truth-coffee",
    name: "Truth Coffee Roasting",
    category: "coffee",
    area: "CBD",
    estimatedCost: 260,
    costMax: 400,
    durationMin: 75,
    duration: "75 min",
    description: "Voted best coffee shop in the world. Steampunk-themed interior with incredible coffee and conversation vibes.",
    vibe: ["introvert", "chill"],
    tags: ["coffee", "culture", "indoor"],
    image: "☕",
    rating: 4.8,
    requiresCar: false,
    websiteUrl: "https://www.truthcoffee.com",
    menuUrl: "https://www.truthcoffee.com/pages/menu",
    reviews: [
      { author: "Nadia K.", rating: 5, text: "The steampunk interior is SO cool — conversation flows naturally because there's so much to look at. Coffee is outstanding.", timeAgo: "1 week ago" },
      { author: "Chris B.", rating: 5, text: "Voted best coffee shop in the world for a reason. My date was impressed I even knew about this place. Order the cold brew!", timeAgo: "2 weeks ago" },
      { author: "Fatima A.", rating: 4, text: "Incredible atmosphere but can be busy on weekends. The breakfast menu is also great if you're doing a morning date.", timeAgo: "1 month ago" },
    ],
  },
  {
    id: "rooftop-shift",
    name: "Rooftop Bar at The Shift",
    category: "nightlife",
    area: "CBD",
    estimatedCost: 560,
    costMax: 900,
    durationMin: 120,
    duration: "2 hours",
    description: "Craft cocktails with panoramic city views from a trendy rooftop. Perfect for a sunset start or nightcap.",
    vibe: ["extrovert", "romantic"],
    tags: ["nightlife", "romantic", "luxury"],
    image: "🍸",
    rating: 4.5,
    requiresCar: false,
  },
  {
    id: "bo-kaap-walk",
    name: "Bo-Kaap Walking Tour",
    category: "culture",
    area: "Bo-Kaap",
    estimatedCost: 0,
    durationMin: 60,
    duration: "1 hour",
    description: "Wander through the colourful streets of the Bo-Kaap. Learn the history, take stunning photos, and soak in the charm.",
    vibe: ["introvert", "romantic", "chill"],
    tags: ["culture", "scenic", "free", "romantic"],
    image: "🏘️",
    rating: 4.5,
    requiresCar: false,
  },
  {
    id: "bo-kaap-cooking",
    name: "Cape Malay Cooking Class",
    category: "food",
    area: "Bo-Kaap",
    estimatedCost: 1700,
    costMax: 2000,
    durationMin: 180,
    duration: "3 hours",
    description: "Learn to cook traditional Cape Malay dishes together in a local home. Includes the meal you make! Intimate and unique.",
    vibe: ["introvert", "romantic"],
    tags: ["food", "culture", "romantic", "indoor"],
    image: "👨‍🍳",
    rating: 4.9,
    requiresCar: false,
    websiteUrl: "https://www.bokaapcookingclass.co.za",
    reviews: [
      { author: "Priya S.", rating: 5, text: "The most unique date we've ever been on! Cooking together in a real Bo-Kaap home. The aunty who hosted us was warm and hilarious.", timeAgo: "1 week ago" },
      { author: "Michael T.", rating: 5, text: "We learned to make bobotie and samoosas. The best part was eating what we cooked together. My partner still talks about it!", timeAgo: "3 weeks ago" },
    ],
  },

  // ─── FOOD & MARKETS ───
  {
    id: "ozcf-market",
    name: "Oranjezicht City Farm Market",
    category: "food",
    area: "De Waterkant",
    estimatedCost: 500,
    costMax: 700,
    durationMin: 90,
    duration: "90 min",
    description: "Fresh produce, artisan foods, and local crafts in a vibrant weekend market with harbour views.",
    vibe: ["extrovert", "chill"],
    tags: ["food", "culture", "fun"],
    deals: "Saturdays & Sundays only!",
    image: "🥘",
    rating: 4.5,
    requiresCar: false,
    websiteUrl: "https://www.ozcf.co.za",
  },
  {
    id: "neighbourgoods",
    name: "Neighbourgoods Market",
    category: "food",
    area: "Woodstock",
    estimatedCost: 440,
    costMax: 650,
    durationMin: 90,
    duration: "90 min",
    description: "Street food from around the world, craft vendors, and live music. Cape Town's favourite Saturday market.",
    vibe: ["extrovert", "chill"],
    tags: ["food", "culture", "fun"],
    deals: "Saturdays only! 9am – 2pm",
    image: "🎪",
    rating: 4.5,
    requiresCar: false,
    websiteUrl: "https://www.neighbourgoodsmarket.co.za",
  },
  {
    id: "harbour-house",
    name: "Harbour House Kalk Bay",
    category: "food",
    area: "Kalk Bay",
    estimatedCost: 1200,
    costMax: 1800,
    durationMin: 120,
    duration: "2 hours",
    description: "Upscale seafood right on the ocean. Waves literally crash against the windows. One of Cape Town's most romantic restaurants.",
    vibe: ["romantic", "introvert"],
    tags: ["food", "romantic", "luxury", "scenic"],
    image: "🦞",
    rating: 4.7,
    requiresCar: true,
    websiteUrl: "https://www.harbourhouse.co.za",
    menuUrl: "https://www.harbourhouse.co.za/kalk-bay-menu/",
    reviews: [
      { author: "Rebecca L.", rating: 5, text: "Waves literally crash against the windows. Most romantic restaurant in Cape Town. The seafood platter for two is incredible.", timeAgo: "4 days ago" },
      { author: "Daniel G.", rating: 5, text: "Took my wife here for our anniversary. The setting is unmatched — arrive before sunset for the best experience.", timeAgo: "2 weeks ago" },
      { author: "Amara O.", rating: 4, text: "Beautiful but pricey. Worth it for a special occasion. Book a window table — that's the whole point!", timeAgo: "1 month ago" },
    ],
  },
  {
    id: "kalk-bay-stroll",
    name: "Kalk Bay Village Stroll",
    category: "chill",
    area: "Kalk Bay",
    estimatedCost: 200,
    costMax: 400,
    durationMin: 90,
    duration: "90 min",
    description: "Browse antique shops, art galleries, and quirky bookstores in this charming seaside village. Grab fish & chips at Kalky's!",
    vibe: ["introvert", "romantic", "chill"],
    tags: ["culture", "scenic", "romantic"],
    image: "🎣",
    rating: 4.5,
    requiresCar: true,
  },

  // ─── ADVENTURE & FUN ───
  {
    id: "cave-golf",
    name: "Cave Golf",
    category: "adventure",
    area: "Canal Walk",
    estimatedCost: 280,
    durationMin: 90,
    duration: "90 min",
    description: "Glow-in-the-dark mini golf in a cave setting. Fun, competitive, and great for breaking the ice!",
    vibe: ["extrovert", "adventurous"],
    tags: ["fun", "adventure", "indoor"],
    deals: "Couples special on Tuesdays — 2-for-1!",
    image: "⛳",
    rating: 4.3,
    requiresCar: false,
    websiteUrl: "https://www.cavegolf.co.za",
    reviews: [
      { author: "Bongani M.", rating: 4, text: "Such a fun date! The glow-in-the-dark setup makes it super playful. Great ice breaker for a first date.", timeAgo: "1 week ago" },
      { author: "Kelly R.", rating: 4, text: "We made it competitive and the loser had to buy dinner. Really fun and different from the usual dinner-and-a-movie.", timeAgo: "3 weeks ago" },
    ],
  },
  {
    id: "paragliding",
    name: "Tandem Paragliding",
    category: "adventure",
    area: "Signal Hill",
    estimatedCost: 3200,
    durationMin: 30,
    duration: "30 min",
    description: "Fly off Signal Hill and land on the beach! An adrenaline-pumping experience with insane views of Cape Town.",
    vibe: ["adventurous", "extrovert"],
    tags: ["adventure", "active", "scenic"],
    deals: "Book for two and ask for a discount",
    image: "🪂",
    rating: 4.9,
    requiresCar: false,
    websiteUrl: "https://www.paraglidecapetown.com",
    reviews: [
      { author: "Josh P.", rating: 5, text: "BEST EXPERIENCE OF MY LIFE! Flying over Camps Bay and landing on the beach. My girlfriend screamed the whole time but loved every second.", timeAgo: "5 days ago" },
      { author: "Lebo N.", rating: 5, text: "If you want to impress her, do this. The adrenaline rush brings you closer together. Photos and video included!", timeAgo: "2 weeks ago" },
    ],
  },
  {
    id: "abseil-table-mountain",
    name: "Table Mountain Abseil",
    category: "adventure",
    area: "Table Mountain",
    estimatedCost: 2500,
    durationMin: 60,
    duration: "1 hour",
    description: "Abseil off the top of Table Mountain — 112m drop! The world's highest commercial abseil. Not for the faint-hearted!",
    vibe: ["adventurous", "extrovert"],
    tags: ["adventure", "active", "scenic"],
    image: "🧗",
    rating: 4.8,
    requiresCar: false,
    websiteUrl: "https://www.abseilafrica.co.za",
  },
  {
    id: "kayak-simons-town",
    name: "Kayaking with Penguins",
    category: "adventure",
    area: "Simon's Town",
    estimatedCost: 1200,
    durationMin: 120,
    duration: "2 hours",
    description: "Paddle alongside African penguins in Simon's Town harbour. Guides included. A once-in-a-lifetime date!",
    vibe: ["adventurous", "romantic"],
    tags: ["adventure", "nature", "active"],
    image: "🛶",
    rating: 4.7,
    requiresCar: true,
    websiteUrl: "https://www.kayakcapetown.co.za",
  },

  // ─── DESSERT & SWEET SPOTS ───
  {
    id: "unframed-icecream",
    name: "Unframed Ice Cream",
    category: "dessert",
    area: "De Waterkant",
    estimatedCost: 180,
    durationMin: 30,
    duration: "30 min",
    description: "Artisan ice cream made with local ingredients. Perfect sweet stop between activities.",
    vibe: ["romantic", "chill"],
    tags: ["dessert", "fun", "quick"],
    image: "🍦",
    rating: 4.4,
    requiresCar: false,
    websiteUrl: "https://www.unframed.co.za",
    menuUrl: "https://www.unframed.co.za/flavours",
  },
  {
    id: "honest-chocolate",
    name: "Honest Chocolate Café",
    category: "dessert",
    area: "CBD",
    estimatedCost: 240,
    costMax: 360,
    durationMin: 45,
    duration: "45 min",
    description: "Bean-to-bar chocolate in a cozy courtyard café. Try the hot chocolate and truffles — pure indulgence.",
    vibe: ["introvert", "romantic", "chill"],
    tags: ["dessert", "romantic", "indoor"],
    image: "🍫",
    rating: 4.6,
    requiresCar: false,
    websiteUrl: "https://www.honestchocolate.co.za",
    menuUrl: "https://www.honestchocolate.co.za/pages/cafe",
  },

  // ─── CHILL & PICNIC ───
  {
    id: "green-point-picnic",
    name: "Green Point Park Picnic",
    category: "chill",
    area: "Green Point",
    estimatedCost: 350,
    durationMin: 120,
    duration: "2 hours",
    description: "Beautiful urban park with a biodiversity garden. Pack a picnic basket and enjoy the sunshine together.",
    vibe: ["romantic", "chill", "introvert"],
    tags: ["romantic", "nature", "free"],
    image: "🧺",
    rating: 4.3,
    requiresCar: false,
    prepTips: [
      "Pack a proper picnic: cheese board, baguette, grapes, cold meats, hummus",
      "Bring a big blanket and cushions for comfort",
      "Add a small bouquet of her favourite flowers",
      "Bring sparkling water or juice with wine glasses (real ones!)",
      "Pack wet wipes and a small cutting board",
      "A Bluetooth speaker with a soft playlist goes a long way",
    ],
  },
  {
    id: "sea-point-promenade",
    name: "Sea Point Promenade Walk",
    category: "chill",
    area: "Sea Point",
    estimatedCost: 0,
    durationMin: 90,
    duration: "90 min",
    description: "Scenic seaside walk along Cape Town's most vibrant promenade. People watching, art, and ocean views.",
    vibe: ["chill", "romantic"],
    tags: ["free", "scenic", "beach", "romantic"],
    image: "🚶",
    rating: 4.4,
    requiresCar: false,
  },
  {
    id: "observatory-lower-main",
    name: "Lower Main Road Obs",
    category: "nightlife",
    area: "Observatory",
    estimatedCost: 400,
    durationMin: 120,
    duration: "2 hours",
    description: "Bohemian bars, live music, and quirky restaurants in Cape Town's most eclectic neighbourhood. Great for a fun night out.",
    vibe: ["extrovert", "adventurous"],
    tags: ["nightlife", "fun", "culture"],
    image: "🎵",
    rating: 4.3,
    requiresCar: false,
  },

  // ─── COFFEE ───
  {
    id: "rosetta-roastery",
    name: "Rosetta Roastery",
    category: "coffee",
    area: "De Waterkant",
    estimatedCost: 200,
    durationMin: 60,
    duration: "1 hour",
    description: "Specialty single-origin coffee in a minimal, design-forward space. Great for quiet morning dates.",
    vibe: ["introvert", "chill"],
    tags: ["coffee", "indoor"],
    image: "☕",
    rating: 4.6,
    requiresCar: false,
    websiteUrl: "https://www.rosettaroastery.com",
  },
  {
    id: "espresso-lab",
    name: "Espresso Lab",
    category: "coffee",
    area: "CBD",
    estimatedCost: 220,
    durationMin: 60,
    duration: "1 hour",
    description: "Trendy micro-roastery with a lab-like setup. Watch them brew with precision. Great conversation starter.",
    vibe: ["introvert", "chill"],
    tags: ["coffee", "culture", "indoor"],
    image: "🧪",
    rating: 4.5,
    requiresCar: false,
    websiteUrl: "https://www.espressolab.co.za",
  },

  // ─── WINELANDS ───
  {
    id: "stellenbosch-wine",
    name: "Stellenbosch Wine Route",
    category: "food",
    area: "Stellenbosch",
    estimatedCost: 800,
    durationMin: 300,
    duration: "5 hours",
    description: "Visit 2-3 stunning wine estates in the heart of the Winelands. Tastings, cheese platters, and oak-lined streets.",
    vibe: ["romantic", "chill", "introvert"],
    tags: ["food", "romantic", "luxury", "culture"],
    deals: "Consider a wine tram for a car-free option!",
    image: "🍇",
    rating: 4.8,
    requiresCar: true,
    prepTips: ["Book tastings in advance — popular estates fill up", "Spier, Delaire Graff, and Jordan are great picks", "Have a designated driver or book a wine tour"],
    websiteUrl: "https://www.wineroute.co.za",
  },
  {
    id: "franschhoek-tram",
    name: "Franschhoek Wine Tram",
    category: "food",
    area: "Franschhoek",
    estimatedCost: 640,
    durationMin: 300,
    duration: "5 hours",
    description: "Hop-on-hop-off wine tram through the Franschhoek valley. Visit multiple estates without driving. Pure romance!",
    vibe: ["romantic", "chill"],
    tags: ["food", "romantic", "luxury", "culture", "scenic"],
    deals: "Book weeks in advance — sells out fast!",
    image: "🚂",
    rating: 4.9,
    requiresCar: true,
    prepTips: ["Book at least 2 weeks in advance", "Pack sunscreen and a hat", "Eat breakfast — the tastings add up!"],
    websiteUrl: "https://www.winetram.co.za",
    reviews: [
      { author: "Sophie G.", rating: 5, text: "The most romantic day trip from Cape Town! The tram is charming and the wine estates are stunning. We did the Blue Line.", timeAgo: "1 week ago" },
      { author: "Willem J.", rating: 5, text: "Book WEEKS in advance — I cannot stress this enough. We almost missed out. Every estate has incredible wine and views.", timeAgo: "3 weeks ago" },
      { author: "Aimee R.", rating: 4, text: "Have breakfast before you go — the wine hits fast on an empty stomach! Such a gorgeous experience though.", timeAgo: "1 month ago" },
    ],
  },

  // ─── DURBANVILLE & BLOUBERG ───
  {
    id: "durbanville-wine",
    name: "Durbanville Wine Valley",
    category: "food",
    area: "Durbanville",
    estimatedCost: 560,
    durationMin: 180,
    duration: "3 hours",
    description: "Lesser-known wine farms with stunning views. Less crowds, more intimate. Try D'Aria or Hillcrest for great setups.",
    vibe: ["romantic", "chill", "introvert"],
    tags: ["food", "romantic", "scenic"],
    image: "🏡",
    rating: 4.4,
    requiresCar: true,
    websiteUrl: "https://www.durbanvillewine.co.za",
  },
  {
    id: "blouberg-sunset",
    name: "Bloubergstrand Sunset",
    category: "beach",
    area: "Bloubergstrand",
    estimatedCost: 0,
    durationMin: 90,
    duration: "90 min",
    description: "The iconic Table Mountain photo spot across the bay. Long beach walk with golden sunset views.",
    vibe: ["romantic", "chill"],
    tags: ["beach", "scenic", "free", "romantic"],
    image: "📸",
    rating: 4.5,
    requiresCar: true,
  },

  // ─── SPA & PAMPERING ───
  {
    id: "couples-spa",
    name: "Couples Spa Treatment",
    category: "chill",
    area: "V&A Waterfront",
    estimatedCost: 2400,
    durationMin: 120,
    duration: "2 hours",
    description: "Side-by-side massages, hot stone therapy, and relaxation in a luxury setting. The ultimate pampering date.",
    vibe: ["romantic", "chill", "introvert"],
    tags: ["romantic", "luxury", "indoor"],
    image: "💆",
    rating: 4.8,
    requiresCar: false,
    websiteUrl: "https://www.onespagroup.co.za",
    menuUrl: "https://www.onespagroup.co.za/treatments/",
  },
  {
    id: "wellness-massage",
    name: "Hot Stone Couples Massage",
    category: "chill",
    area: "Camps Bay",
    estimatedCost: 1800,
    durationMin: 90,
    duration: "90 min",
    description: "Relaxing hot stone massage for two with ocean views. Includes welcome drinks and a relaxation lounge.",
    vibe: ["romantic", "chill"],
    tags: ["romantic", "luxury", "indoor"],
    image: "🧖",
    rating: 4.7,
    requiresCar: false,
    websiteUrl: "https://www.12apostleshotel.com/spa",
  },

  // ─── CHOCOLATE & SWEET EXPERIENCES ───
  {
    id: "chocolate-tasting",
    name: "Chocolate Tasting Experience",
    category: "dessert",
    area: "Constantia",
    estimatedCost: 400,
    durationMin: 75,
    duration: "75 min",
    description: "Guided bean-to-bar chocolate tasting at a boutique chocolatier. Learn to pair chocolate with wine. Sweet and sophisticated!",
    vibe: ["romantic", "introvert", "chill"],
    tags: ["dessert", "romantic", "culture", "indoor"],
    image: "🍫",
    rating: 4.6,
    requiresCar: true,
    websiteUrl: "https://www.belgianchocolate.co.za",
  },

  // ─── MORE ROMANTIC ACTIVITIES ───
  {
    id: "pottery-class",
    name: "Couples Pottery Class",
    category: "culture",
    area: "Woodstock",
    estimatedCost: 700,
    durationMin: 120,
    duration: "2 hours",
    description: "Get your hands dirty together making pottery. Think Ghost movie vibes! Great for laughs and a unique keepsake.",
    vibe: ["romantic", "chill", "introvert"],
    tags: ["culture", "romantic", "fun", "indoor"],
    image: "🏺",
    rating: 4.5,
    requiresCar: false,
    websiteUrl: "https://www.theceramicstudio.co.za",
    reviews: [
      { author: "Yolanda M.", rating: 5, text: "Ghost movie vibes! We laughed so hard at our terrible pottery but it was the best date. You get to keep what you make!", timeAgo: "1 week ago" },
      { author: "Alex H.", rating: 4, text: "Really fun and creative. The instructor was great. We now have matching (ugly) mugs and it's our favourite inside joke.", timeAgo: "2 weeks ago" },
    ],
  },
  {
    id: "horse-riding",
    name: "Beach Horse Riding",
    category: "adventure",
    area: "Noordhoek",
    estimatedCost: 1400,
    durationMin: 90,
    duration: "90 min",
    description: "Ride horses along Noordhoek's wild beach at sunset. Incredibly romantic and unforgettable. No experience needed!",
    vibe: ["romantic", "adventurous"],
    tags: ["adventure", "romantic", "nature", "scenic"],
    image: "🐴",
    rating: 4.9,
    requiresCar: true,
    websiteUrl: "https://www.horseridingcapetown.co.za",
    prepTips: ["Wear long pants and closed shoes", "Book the sunset ride for maximum romance", "Bring a camera — the photos are incredible"],
    reviews: [
      { author: "Megan S.", rating: 5, text: "Riding horses on the beach at sunset — it doesn't get more romantic than this! The guides were amazing and patient with beginners.", timeAgo: "3 days ago" },
      { author: "Ruan V.", rating: 5, text: "My girlfriend's dream date. She cried happy tears. The beach is wild and beautiful. Book the sunset slot!", timeAgo: "2 weeks ago" },
    ],
  },
  {
    id: "stargazing",
    name: "Stargazing Experience",
    category: "scenic",
    area: "Cape Point",
    estimatedCost: 600,
    durationMin: 120,
    duration: "2 hours",
    description: "Guided stargazing away from city lights. Learn constellations together under the Southern Hemisphere sky. Magical!",
    vibe: ["romantic", "introvert", "chill"],
    tags: ["romantic", "nature", "scenic"],
    image: "🌌",
    rating: 4.7,
    requiresCar: true,
    prepTips: ["Bring warm blankets — it gets cold at night", "Pack hot chocolate in a thermos", "Check moon phase — less moon = more stars"],
  },
  {
    id: "paint-sip",
    name: "Paint & Sip Night",
    category: "culture",
    area: "De Waterkant",
    estimatedCost: 700,
    durationMin: 120,
    duration: "2 hours",
    description: "Paint a masterpiece together while sipping wine. No art skills needed — just fun, laughs, and a canvas to take home.",
    vibe: ["extrovert", "romantic", "chill"],
    tags: ["culture", "fun", "romantic", "indoor"],
    image: "🎨",
    rating: 4.4,
    requiresCar: false,
    websiteUrl: "https://www.paintsipct.co.za",
  },
  {
    id: "helicopter-tour",
    name: "Helicopter Scenic Flight",
    category: "adventure",
    area: "V&A Waterfront",
    estimatedCost: 4500,
    durationMin: 20,
    duration: "20 min",
    description: "Fly over Table Mountain, the Twelve Apostles, and Camps Bay. The ultimate wow-factor date for a special occasion.",
    vibe: ["adventurous", "romantic"],
    tags: ["adventure", "scenic", "luxury"],
    image: "🚁",
    rating: 4.9,
    requiresCar: false,
    websiteUrl: "https://www.nachelicopters.co.za",
  },
  {
    id: "flower-market",
    name: "Flower Market & Bouquet",
    category: "chill",
    area: "CBD",
    estimatedCost: 200,
    durationMin: 30,
    duration: "30 min",
    description: "Pick out fresh flowers together at Adderley Street's famous flower market. A sweet, thoughtful touch to any date.",
    vibe: ["romantic", "chill"],
    tags: ["romantic", "fun"],
    image: "💐",
    rating: 4.3,
    requiresCar: false,
    prepTips: ["Go early for the best selection", "Ask her favourite colour — pick flowers to match", "If you're brave, surprise her with a pre-made bouquet"],
  },

  // ─── CBD FINE DINING (CCID MAP) ───
  {
    id: "belly-of-the-beast",
    name: "Belly of the Beast",
    category: "food",
    area: "CBD",
    estimatedCost: 1400,
    costMax: 2000,
    durationMin: 120,
    duration: "2 hours",
    description: "Intimate 24-seat fine dining with a surprise tasting menu using locally sourced ingredients. One of Cape Town's most acclaimed hidden gems.",
    vibe: ["romantic", "introvert"],
    tags: ["food", "romantic", "luxury", "indoor"],
    image: "🍽️",
    rating: 4.9,
    requiresCar: false,
    websiteUrl: "https://www.bellyofthebeast.co.za",
    prepTips: ["Book well in advance, only 24 seats", "It's a set menu so no need to decide, just enjoy", "Dress smart casual"],
    reviews: [
      { author: "Zinhle M.", rating: 5, text: "The most intimate dining experience in Cape Town. Every course was a surprise and a delight. Perfect for a special date.", timeAgo: "1 week ago" },
    ],
  },
  {
    id: "fyn-restaurant",
    name: "FYN Restaurant",
    category: "food",
    area: "CBD",
    estimatedCost: 3000,
    costMax: 4500,
    durationMin: 150,
    duration: "2.5 hours",
    description: "Japanese-inspired fine dining on Parliament Street. Ranked among Africa's best restaurants. A celebration-worthy experience.",
    vibe: ["romantic", "introvert"],
    tags: ["food", "romantic", "luxury", "indoor"],
    image: "🥢",
    rating: 4.9,
    requiresCar: false,
    websiteUrl: "https://www.fynrestaurant.com",
    prepTips: ["Book at least 2 weeks ahead", "Opt for the wine pairing, it's exceptional", "Smart dress code"],
  },
  {
    id: "grub-and-vine",
    name: "Grub & Vine",
    category: "food",
    area: "CBD",
    estimatedCost: 800,
    costMax: 1200,
    durationMin: 120,
    duration: "2 hours",
    description: "Relaxed fine dining on Bree Street. Seasonal menu with incredible wine pairings. Beautiful interiors and warm service.",
    vibe: ["romantic", "chill"],
    tags: ["food", "romantic", "indoor"],
    image: "🍷",
    rating: 4.7,
    requiresCar: false,
    websiteUrl: "https://www.grubandvine.com",
  },
  {
    id: "chefs-warehouse",
    name: "Chef's Warehouse & Canteen",
    category: "food",
    area: "CBD",
    estimatedCost: 900,
    costMax: 1400,
    durationMin: 120,
    duration: "2 hours",
    description: "Tapas-style sharing dishes in a buzzing Bree Street setting. No bookings, first come first served. Worth the wait!",
    vibe: ["romantic", "extrovert"],
    tags: ["food", "romantic", "fun", "indoor"],
    image: "👨‍🍳",
    rating: 4.8,
    requiresCar: false,
    websiteUrl: "https://www.chefswarehouse.co.za",
    prepTips: ["No reservations, arrive by 17:30 for best chance", "Go hungry, the tapas portions are generous", "Share everything, that's the whole point"],
  },

  // ─── CBD PREMIUM CASUAL (CCID MAP) ───
  {
    id: "mulberry-prince",
    name: "Mulberry & Prince",
    category: "food",
    area: "CBD",
    estimatedCost: 600,
    costMax: 900,
    durationMin: 90,
    duration: "90 min",
    description: "Hip, colourful restaurant on Pepper Street with bold Mediterranean flavours. Great cocktails and gorgeous interiors.",
    vibe: ["romantic", "extrovert"],
    tags: ["food", "romantic", "fun", "indoor"],
    image: "🫒",
    rating: 4.6,
    requiresCar: false,
    websiteUrl: "https://www.mulberryandprince.co.za",
  },
  {
    id: "gigi-rooftop",
    name: "Gigi Rooftop Restaurant",
    category: "food",
    area: "CBD",
    estimatedCost: 700,
    costMax: 1100,
    durationMin: 120,
    duration: "2 hours",
    description: "Mediterranean rooftop dining at Gorgeous George hotel. Stunning city views, great cocktails, and a romantic atmosphere.",
    vibe: ["romantic", "extrovert"],
    tags: ["food", "romantic", "scenic", "nightlife"],
    image: "🌃",
    rating: 4.6,
    requiresCar: false,
    websiteUrl: "https://www.gorgeousgeorge.co.za",
  },
  {
    id: "hemelhuijs",
    name: "Hemelhuijs",
    category: "food",
    area: "CBD",
    estimatedCost: 500,
    costMax: 700,
    durationMin: 90,
    duration: "90 min",
    description: "Beautiful heritage building on Waterkant Street. Seasonal menu with a feminine, sophisticated touch. Perfect for a daytime date.",
    vibe: ["romantic", "introvert", "chill"],
    tags: ["food", "romantic", "indoor"],
    image: "🌸",
    rating: 4.5,
    requiresCar: false,
    websiteUrl: "https://www.hemelhuijs.co.za",
  },
  {
    id: "burger-lobster",
    name: "Burger & Lobster",
    category: "food",
    area: "CBD",
    estimatedCost: 700,
    costMax: 1000,
    durationMin: 90,
    duration: "90 min",
    description: "London import on Wale Street. Choose burger or lobster, each impeccably done. Simple menu, big flavours, great vibes.",
    vibe: ["extrovert", "chill"],
    tags: ["food", "fun", "indoor"],
    image: "🦞",
    rating: 4.5,
    requiresCar: false,
    websiteUrl: "https://www.burgerandlobster.com",
  },

  // ─── CBD CASUAL DINING (CCID MAP) ───
  {
    id: "labotessa",
    name: "Labotessa Terrace & Café",
    category: "food",
    area: "CBD",
    estimatedCost: 600,
    costMax: 900,
    durationMin: 90,
    duration: "90 min",
    description: "Elegant café at the Labotessa boutique hotel overlooking Church Square. Beautiful for a leisurely brunch or lunch date.",
    vibe: ["romantic", "introvert", "chill"],
    tags: ["food", "romantic", "indoor"],
    image: "☕",
    rating: 4.6,
    requiresCar: false,
  },
  {
    id: "companys-garden-restaurant",
    name: "Company's Garden Restaurant",
    category: "food",
    area: "CBD",
    estimatedCost: 400,
    costMax: 600,
    durationMin: 90,
    duration: "90 min",
    description: "Lovely outdoor restaurant in Cape Town's historic Company's Garden. Shaded by oaks, surrounded by squirrels. Peaceful and charming.",
    vibe: ["romantic", "chill", "introvert"],
    tags: ["food", "romantic", "nature"],
    image: "🌿",
    rating: 4.4,
    requiresCar: false,
  },
  {
    id: "clarkes",
    name: "Clarke's Bar & Dining Room",
    category: "food",
    area: "CBD",
    estimatedCost: 500,
    costMax: 800,
    durationMin: 90,
    duration: "90 min",
    description: "Heritage Square gem with a wood-fired oven and open kitchen. Known for incredible steaks and seasonal dishes. Great date energy.",
    vibe: ["romantic", "chill"],
    tags: ["food", "romantic", "indoor"],
    image: "🥩",
    rating: 4.6,
    requiresCar: false,
  },

  // ─── CBD AFRICAN CUISINE (CCID MAP) ───
  {
    id: "addis-in-cape",
    name: "Addis in Cape Ethiopian",
    category: "food",
    area: "CBD",
    estimatedCost: 400,
    costMax: 600,
    durationMin: 90,
    duration: "90 min",
    description: "Authentic Ethiopian dining on Long Street. Share injera platters and eat with your hands. Fun, intimate, and different!",
    vibe: ["adventurous", "romantic"],
    tags: ["food", "culture", "fun", "indoor"],
    image: "🫓",
    rating: 4.5,
    requiresCar: false,
    prepTips: ["You eat with your hands (injera bread), embrace it!", "Great for adventurous eaters", "Try the coffee ceremony at the end"],
  },

  // ─── CBD ASIAN (CCID MAP) ───
  {
    id: "haiku-cbd",
    name: "Haiku",
    category: "food",
    area: "CBD",
    estimatedCost: 500,
    costMax: 800,
    durationMin: 90,
    duration: "90 min",
    description: "Atmospheric Asian tapas bar on Burg Street. Dim lighting, sharing plates, and creative cocktails. Ideal date night spot.",
    vibe: ["romantic", "introvert"],
    tags: ["food", "romantic", "indoor", "nightlife"],
    image: "🥟",
    rating: 4.5,
    requiresCar: false,
  },
  {
    id: "south-china-dim-sum",
    name: "South China Dim Sum Bar",
    category: "food",
    area: "CBD",
    estimatedCost: 400,
    costMax: 600,
    durationMin: 75,
    duration: "75 min",
    description: "Long Street dim sum spot with steaming baskets and neon vibes. Fun, affordable, and perfect for sharing.",
    vibe: ["extrovert", "chill"],
    tags: ["food", "fun", "indoor"],
    image: "🥡",
    rating: 4.4,
    requiresCar: false,
  },

  // ─── CBD ITALIAN (CCID MAP) ───
  {
    id: "carne-sa-keerom",
    name: "Carné on Keerom",
    category: "food",
    area: "CBD",
    estimatedCost: 800,
    costMax: 1200,
    durationMin: 120,
    duration: "2 hours",
    description: "Classic Italian fine dining on Keerom Street. Rich pastas, excellent steaks, and a warm, candlelit atmosphere.",
    vibe: ["romantic", "introvert"],
    tags: ["food", "romantic", "luxury", "indoor"],
    image: "🍝",
    rating: 4.7,
    requiresCar: false,
    websiteUrl: "https://www.carne.co.za",
  },
  {
    id: "villa-47",
    name: "Villa 47",
    category: "food",
    area: "CBD",
    estimatedCost: 500,
    costMax: 800,
    durationMin: 90,
    duration: "90 min",
    description: "Trendy Italian spot on Bree Street with pizza, pasta, and great cocktails. Lively atmosphere, perfect for a fun date.",
    vibe: ["extrovert", "chill"],
    tags: ["food", "fun", "indoor"],
    image: "🍕",
    rating: 4.4,
    requiresCar: false,
  },

  // ─── CBD COFFEE SHOPS (CCID MAP) ───
  {
    id: "charly-bakery",
    name: "Charly's Bakery",
    category: "coffee",
    area: "CBD",
    estimatedCost: 200,
    costMax: 350,
    durationMin: 60,
    duration: "1 hour",
    description: "Famous from the Cake Boss! Incredible cakes, pastries, and coffee in a colourful Canterbury Street café.",
    vibe: ["chill", "romantic"],
    tags: ["coffee", "dessert", "fun", "indoor"],
    image: "🎂",
    rating: 4.5,
    requiresCar: false,
    websiteUrl: "https://www.charlysbakery.co.za",
  },
  {
    id: "deluxe-coffeeworks",
    name: "Deluxe Coffeeworks",
    category: "coffee",
    area: "CBD",
    estimatedCost: 180,
    costMax: 280,
    durationMin: 45,
    duration: "45 min",
    description: "Cool roastery café on Bree Street. Specialty coffee, great pastries, and a laid-back vibe. Perfect morning date starter.",
    vibe: ["chill", "introvert"],
    tags: ["coffee", "indoor"],
    image: "☕",
    rating: 4.5,
    requiresCar: false,
  },

  // ─── CBD COCKTAIL BARS (CCID MAP) ───
  {
    id: "harringtons-lounge",
    name: "Harrington's Cocktail Lounge",
    category: "nightlife",
    area: "CBD",
    estimatedCost: 400,
    costMax: 700,
    durationMin: 90,
    duration: "90 min",
    description: "Speakeasy-style cocktail bar in a heritage building on Harrington Street. Craft cocktails, moody lighting, and jazz vibes.",
    vibe: ["romantic", "introvert"],
    tags: ["nightlife", "romantic", "indoor"],
    image: "🍸",
    rating: 4.6,
    requiresCar: false,
  },
  {
    id: "the-gin-bar",
    name: "The Gin Bar",
    category: "nightlife",
    area: "CBD",
    estimatedCost: 350,
    costMax: 600,
    durationMin: 90,
    duration: "90 min",
    description: "Hidden gin bar on Wale Street with over 100 gins. Cozy, intimate, and perfect for a sophisticated nightcap.",
    vibe: ["romantic", "introvert"],
    tags: ["nightlife", "romantic", "indoor"],
    image: "🫒",
    rating: 4.5,
    requiresCar: false,
  },
  {
    id: "tjing-tjing-rooftop",
    name: "Tjing Tjing Rooftop Bar",
    category: "nightlife",
    area: "CBD",
    estimatedCost: 400,
    costMax: 700,
    durationMin: 90,
    duration: "90 min",
    description: "Japanese-inspired rooftop bar on Longmarket Street. Lantern-lit terrace, sake cocktails, and stunning city views at night.",
    vibe: ["romantic", "extrovert"],
    tags: ["nightlife", "romantic", "scenic"],
    image: "🏮",
    rating: 4.7,
    requiresCar: false,
  },
  {
    id: "fable-bar",
    name: "Fable",
    category: "nightlife",
    area: "CBD",
    estimatedCost: 300,
    costMax: 600,
    durationMin: 90,
    duration: "90 min",
    description: "Underground cocktail bar on Loop Street with a mysterious, fairy-tale atmosphere. Creative cocktails and great music.",
    vibe: ["adventurous", "extrovert"],
    tags: ["nightlife", "fun", "indoor"],
    image: "📖",
    rating: 4.4,
    requiresCar: false,
  },
  {
    id: "culture-wine-bar",
    name: "Culture Wine Bar",
    category: "nightlife",
    area: "CBD",
    estimatedCost: 400,
    costMax: 700,
    durationMin: 90,
    duration: "90 min",
    description: "Sophisticated wine bar on Bree Street. Curated SA wine list, charcuterie boards, and a relaxed, grown-up atmosphere.",
    vibe: ["romantic", "introvert", "chill"],
    tags: ["nightlife", "romantic", "indoor"],
    image: "🍷",
    rating: 4.5,
    requiresCar: false,
  },

  // ─── NON-TRADITIONAL / CREATIVE DATES ───
  {
    id: "pottery-painting",
    name: "Pottery Painting Date",
    category: "culture",
    area: "Woodstock",
    estimatedCost: 400,
    costMax: 600,
    durationMin: 120,
    duration: "2 hours",
    description: "Paint ceramics together at a cozy Woodstock studio. Keep your creations as a memory of the date.",
    vibe: ["chill", "romantic", "introvert"],
    tags: ["culture", "fun", "creative", "indoor"],
    image: "🏺",
    rating: 4.6,
    requiresCar: false,
    prepTips: ["Wear clothes you don't mind getting paint on", "Pick matching pieces to paint for each other"],
  },
  {
    id: "comedy-show",
    name: "Live Comedy Night",
    category: "nightlife",
    area: "CBD",
    estimatedCost: 300,
    costMax: 500,
    durationMin: 90,
    duration: "90 min",
    description: "Catch a live stand-up comedy show. Laughing together is the fastest way to connect.",
    vibe: ["extrovert", "chill"],
    tags: ["fun", "nightlife", "indoor"],
    image: "🎤",
    rating: 4.5,
    requiresCar: false,
  },
  {
    id: "stargazing-observatory",
    name: "Stargazing at the Observatory",
    category: "culture",
    area: "Observatory",
    estimatedCost: 200,
    costMax: 350,
    durationMin: 90,
    duration: "90 min",
    description: "Guided stargazing session at the SA Astronomical Observatory. Romantic, nerdy, and totally unique.",
    vibe: ["introvert", "romantic"],
    tags: ["romantic", "culture", "nature"],
    image: "🔭",
    rating: 4.7,
    requiresCar: false,
    prepTips: ["Bring a blanket and hot chocolate", "Check the calendar for open nights"],
  },
  {
    id: "cooking-class",
    name: "Couples Cooking Class",
    category: "food",
    area: "De Waterkant",
    estimatedCost: 800,
    costMax: 1200,
    durationMin: 150,
    duration: "2.5 hours",
    description: "Learn to cook a 3-course meal together with a professional chef. You eat what you make!",
    vibe: ["romantic", "chill", "extrovert"],
    tags: ["food", "fun", "romantic", "indoor"],
    image: "👨‍🍳",
    rating: 4.8,
    requiresCar: false,
  },
  {
    id: "escape-room",
    name: "Escape Room Challenge",
    category: "adventure",
    area: "CBD",
    estimatedCost: 500,
    costMax: 700,
    durationMin: 75,
    duration: "75 min",
    description: "Solve puzzles and escape a themed room together. Great way to see how you vibe under pressure!",
    vibe: ["adventurous", "extrovert"],
    tags: ["fun", "adventure", "indoor"],
    image: "🔐",
    rating: 4.5,
    requiresCar: false,
  },
  {
    id: "vinyl-record-hunting",
    name: "Vinyl Record Shop Crawl",
    category: "culture",
    area: "CBD",
    estimatedCost: 200,
    costMax: 500,
    durationMin: 90,
    duration: "90 min",
    description: "Browse vintage vinyl shops on Long Street. Pick an album each and swap — a gift that keeps on playing.",
    vibe: ["introvert", "chill"],
    tags: ["culture", "fun", "creative"],
    image: "🎵",
    rating: 4.3,
    requiresCar: false,
  },
  {
    id: "sunrise-hike-picnic",
    name: "Sunrise Hike & Picnic",
    category: "mountain",
    area: "Signal Hill",
    estimatedCost: 100,
    costMax: 250,
    durationMin: 120,
    duration: "2 hours",
    description: "Hike Signal Hill for sunrise and surprise her with a packed picnic at the top. Effort = love.",
    vibe: ["adventurous", "romantic"],
    tags: ["nature", "romantic", "active"],
    image: "🌄",
    rating: 4.9,
    requiresCar: true,
    prepTips: ["Pack croissants, fruit, juice, and a flask of coffee", "Bring a blanket and Bluetooth speaker"],
  },
  {
    id: "street-art-tour",
    name: "Street Art Walking Tour",
    category: "culture",
    area: "Woodstock",
    estimatedCost: 250,
    costMax: 400,
    durationMin: 90,
    duration: "90 min",
    description: "Explore Woodstock's vibrant murals and street art. Great for photos and conversation.",
    vibe: ["chill", "extrovert"],
    tags: ["culture", "fun", "creative"],
    image: "🖼️",
    rating: 4.4,
    requiresCar: false,
  },
  {
    id: "board-game-cafe",
    name: "Board Game Café Night",
    category: "chill",
    area: "Observatory",
    estimatedCost: 200,
    costMax: 400,
    durationMin: 120,
    duration: "2 hours",
    description: "Pick a board game, order coffee or craft beer, and be competitive (in a cute way). Loser buys dessert.",
    vibe: ["introvert", "chill"],
    tags: ["fun", "indoor", "chill"],
    image: "🎲",
    rating: 4.3,
    requiresCar: false,
  },
  {
    id: "kayak-adventure",
    name: "Sea Kayaking",
    category: "adventure",
    area: "Sea Point",
    estimatedCost: 500,
    costMax: 800,
    durationMin: 120,
    duration: "2 hours",
    description: "Paddle along the Atlantic seaboard. Spot dolphins, seals, or penguins. Adventure with a view!",
    vibe: ["adventurous", "extrovert"],
    tags: ["adventure", "nature", "active"],
    image: "🛶",
    rating: 4.6,
    requiresCar: false,
  },
];

// Point-based scoring algorithm
export function scoreActivity(activity: Activity, answers: Partial<QuizAnswer>): number {
  let score = 0;

  if (answers.personality) {
    if (answers.personality === "introvert" && activity.vibe.includes("introvert")) score += 3;
    if (answers.personality === "extrovert" && activity.vibe.includes("extrovert")) score += 3;
    if (answers.personality === "ambivert") score += 1;
  }

  if (answers.setting) {
    if (answers.setting === "beach" && (activity.category === "beach" || activity.tags.includes("beach"))) score += 3;
    if (answers.setting === "mountains" && (activity.category === "mountain" || activity.tags.includes("nature"))) score += 3;
    if (answers.setting === "city" && (activity.category === "culture" || activity.category === "nightlife" || activity.category === "coffee" || activity.tags.includes("culture"))) score += 3;
    if (answers.setting === "winelands" && (activity.area === "Constantia" || activity.area === "Stellenbosch" || activity.area === "Franschhoek" || activity.area === "Durbanville" || activity.tags.includes("food"))) score += 3;
    if (answers.setting === "cozy-indoor" && (activity.category === "coffee" || activity.category === "chill" || activity.tags.includes("indoor") || activity.tags.includes("romantic"))) score += 3;
  }

  if (answers.energy) {
    if (answers.energy === "chill" && activity.vibe.includes("chill")) score += 2;
    if (answers.energy === "active" && (activity.vibe.includes("adventurous") || activity.tags.includes("active"))) score += 2;
    if (answers.energy === "mix") score += 1;
  }

  if (answers.vibe) {
    if (answers.vibe === "nature" && activity.tags.includes("nature")) score += 2;
    if (answers.vibe === "culture" && activity.tags.includes("culture")) score += 2;
    if (answers.vibe === "spontaneous" && activity.tags.includes("fun")) score += 2;
    if (answers.vibe === "romantic" && activity.tags.includes("romantic")) score += 2;
  }

  // Stage-based scoring
  if (answers.stage) {
    if (answers.stage === "first-date" && activity.tags.includes("fun")) score += 2;
    if (answers.stage === "early-dating" && activity.tags.includes("romantic")) score += 1;
    if (answers.stage === "relationship" && activity.tags.includes("romantic")) score += 2;
    if (answers.stage === "anniversary" && activity.tags.includes("luxury")) score += 3;
    if (answers.stage === "anniversary" && activity.tags.includes("romantic")) score += 2;
  }

  return score;
}

export function getRecommendedActivities(answers: Partial<QuizAnswer>): Activity[] {
  const scored = activities
    .filter(a => {
      if (answers.hasCar === false && a.requiresCar) return false;
      return true;
    })
    .map(a => ({ activity: a, score: scoreActivity(a, answers) }))
    .sort((a, b) => b.score - a.score);

  return scored.map(s => s.activity);
}

export function isGreatMatch(activity: Activity, answers: Partial<QuizAnswer>): boolean {
  return scoreActivity(activity, answers) >= 5;
}

export function getNearbyActivities(activityId: string): Activity[] {
  const activity = activities.find(a => a.id === activityId);
  if (!activity?.nearbyIds) return [];
  return activities.filter(a => activity.nearbyIds?.includes(a.id));
}
